priceItem:
  price: 5250
xPriceItem:
  price: 249
order:
  index: 200
unityAsset:
  reference:
    assetGuid: 2430216bfe2132441bfba35b8c2ab6d8
imageItem:
  spriteUid: 1be63077-4a59-4ada-a1dd-3d2055f5e072
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
