---
descriptionItem:
  name: Чертежи хакера
  description: "В этом контейнере содержится как минимум 61 чертежей, в том числе не менее 5 чертежей Тира-2, и есть небольшая вероятность получить чертежи Тира-3."
descriptionBundleItem:
  names: { }
