priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 1d3726ccdebdf5044bbd8fdb913714cc
imageItem:
  spriteUid: b86c4b6f-fa89-4e26-89de-7d7ec6a12fa1
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
