---
descriptionItem:
  name: West Prime
  description:
flavorList:
  collection:
    - |
      West Prime is the largest enterprise founded by Antaeus on the territory of Russia.
      The crystal processing complex is built around a huge crater, 
      which seems to be an undepletable deposit of crystals. 
