priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 39286556-71d7-4817-a249-b7d08d98fcca
order:
  index: 1
unityAsset:
  reference:
    assetGuid: 3dd91ea28469d3945854490936389734
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
