priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 14ec2e8e-0e4d-4a5f-96c6-95811e2d63e8
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 9f6900664dc0f7b4e905f5244a37cd03
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
