itemsContainerItem:
  items:
    - itemBundles:
        - marketItem: -436467641 # matte blue tank paint
      compensation: 7500
      nameLocalizationKey: mattebluetankpaint
    - itemBundles:
        - marketItem: 1448655312 # matte blue weapon paint
      compensation: 7500
      nameLocalizationKey: matteblueweaponpaint
    - itemBundles:
        - marketItem: -431689890 # matte gray tank paint
      compensation: 7500
      nameLocalizationKey: mattegraytankpaint
    - itemBundles:
        - marketItem: 1448809433 # matte gray weapon paint
      compensation: 7500
      nameLocalizationKey: mattegrayweaponpaint
    - itemBundles:
        - marketItem: -497382758 # matte green tank paint
      compensation: 7500
      nameLocalizationKey: mattegreentankpaint
    - itemBundles:
        - marketItem: 1963422797 # matte green weapon paint
      compensation: 7500
      nameLocalizationKey: mattegreenweaponpaint
    - itemBundles:
        - marketItem: -425712005 # matte navi tank paint
      compensation: 7500
      nameLocalizationKey: mattenavitankpaint
    - itemBundles:
        - marketItem: 1449002268 # matte navi weapon paint
      compensation: 7500
      nameLocalizationKey: mattenaviweaponpaint
    - itemBundles:
        - marketItem: 267667571 # matte orange tank paint
      compensation: 7500
      nameLocalizationKey: matteorangetankpaint
    - itemBundles:
        - marketItem: 965487140 # matte orange weapon paint
      compensation: 7500
      nameLocalizationKey: matteorangeweaponpaint
    - itemBundles:
        - marketItem: -1260536244 # matte red tank paint
      compensation: 7500
      nameLocalizationKey: matteredtankpaint
    - itemBundles:
        - marketItem: -230348709 # matte red weapon paint
      compensation: 7500
      nameLocalizationKey: matteredweaponpaint
    - itemBundles:
        - marketItem: -421603854 # matte rose tank paint
      compensation: 7500
      nameLocalizationKey: matterosetankpaint
    - itemBundles:
        - marketItem: 1449134789 # matte rose weapon paint
      compensation: 7500
      nameLocalizationKey: matteroseweaponpaint
    - itemBundles:
        - marketItem: 1940431938 # matte violet tank paint
      compensation: 7500
      nameLocalizationKey: matteviolettankpaint
    - itemBundles:
        - marketItem: 1157994613 # matte violet weapon paint
      compensation: 7500
      nameLocalizationKey: mattevioletweaponpaint
    - itemBundles:
        - marketItem: 190698221 # matte yellow tank paint
      compensation: 7500
      nameLocalizationKey: matteyellowtankpaint
    - itemBundles:
        - marketItem: 1240098922 # matte yellow weapon paint
      compensation: 7500
      nameLocalizationKey: matteyellowweaponpaint

  rareItems:
    - itemBundles:
        - marketItem: -646190818 # matte tank black
      nameLocalizationKey: matteblacktankpaint
    - itemBundles:
        - marketItem: 1958622537 # matte weapon black
      nameLocalizationKey: matteblackweaponpaint
    - itemBundles:
        - marketItem: -48418252 # matte tank white
      nameLocalizationKey: mattewhitetankpaint
    - itemBundles:
        - marketItem: 1977905523 # matte weapon white
      nameLocalizationKey: mattewhiteweaponpaint


userItemTemplate:
  userItemTemplate: 1479807574456
unityAsset:
  reference:
    assetGuid: 480223cad986a584981ac48a0b0accbd
imageItem:
  spriteUid: 1c15315f-d35e-46cf-ae94-534d420df975
order:
  index: 4
priceItem:
  price: 0
xPriceItem:
  price: 150
itemPacks:
  forXPrice:
    - 1
    - 3
    - 10
  forPrice:
packPrice:
  packPrice:
    0: 0
  packXPrice:
    1: 150
    3: 400
    10: 1200
