order:
  index: 1
unityAsset:
  reference:
    assetGuid: 507992ca976181547871221491ac4460
imageItem:
  spriteUid: 35c25e46-d6f3-4842-9154-84a8113976e5
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
