priceItem:
  price: 0
xPriceItem:
  price: 499
order:
  index: 100
unityAsset:
  reference:
    assetGuid: 7065a2f7d8df2ff4b9d9b8afa6a00845
imageItem:
  spriteUid: cd10aff5-e56a-4f07-8574-4df7b7c97586
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
