---
descriptionItem:
  name: Чертежи разведчика
  description: "В этом контейнере содержится как минимум 190 чертежей для модулей «Импульсный прыжок», «Импульсный генератор», «Огненное кольцо», «Взрывная Масса», «Сапёр» и «Камикадзе»."
descriptionBundleItem:
  names: { }
