priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 37e59395-c6fe-4a43-a7f7-412e05448156
order:
  index: 2
unityAsset:
  reference:
    assetGuid: 8f67569bdab7bce4fb4eebd84a304239
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
