priceItem:
  price: 5250
xPriceItem:
  price: 249
order:
  index: 200
unityAsset:
  reference:
    assetGuid: 81041224a9c60444bb589e865ecbb92f
imageItem:
  spriteUid: bce613c6-8fb1-4ca7-8f84-c77d19bb753b
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
