moduleCooldownProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 60000
    - 57778
    - 55556
    - 53333
    - 51111
    - 48889
    - 46667
    - 44444
    - 42222
    - 40000
moduleAmmunitionProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
moduleEffectDurationProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 6000
    - 6333
    - 6667
    - 7000
    - 7333
    - 7667
    - 8000
    - 8333
    - 8667
    - 9000
moduleDamageEffectMinFactorProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1.15
    - 1.18
    - 1.22
    - 1.25
    - 1.28
    - 1.32
    - 1.35
    - 1.38
    - 1.42
    - 1.45
moduleDamageEffectMaxFactorProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1.17
    - 1.5
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 60
        - 40
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Damage
      linearInterpolation: true
      upgradeLevel2Values:
        - 17
        - 50
      unit: percent
      format: 0
      spriteUID: 5538887f-b208-4fb4-ac4a-12223cb09fd3
    - name: Duration
      linearInterpolation: true
      upgradeLevel2Values:
        - 6
        - 9
      unit: sec
      format: 0.0
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
