priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: ed025b49-02d1-42b3-9a3b-ab010a50a771
order:
  index: 25
unityAsset:
  reference:
    assetGuid: d12011c5884881b41baf65ca5674af9f
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
