moduleCooldownProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 90000
    - 86667
    - 83333
    - 80000
    - 76667
    - 73333
    - 70000
    - 66667
    - 63333
    - 60000
moduleAmmunitionProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
moduleEffectMinDamageProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 700.00
    - 738.89
    - 777.78
    - 816.67
    - 855.56
    - 894.44
    - 933.33
    - 972.22
    - 1011.11
    - 1050.00
moduleEffectMaxDamageProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1000.00
    - 1055.56
    - 1111.11
    - 1166.67
    - 1222.22
    - 1277.78
    - 1333.33
    - 1388.89
    - 1444.44
    - 1500.00
moduleMineEffectImpactProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 3.00
    - 3.17
    - 3.33
    - 3.50
    - 3.67
    - 3.83
    - 4.00
    - 4.17
    - 4.33
    - 4.50
moduleMineEffectHideRangeProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 25.00
    - 24.07
    - 23.15
    - 22.22
    - 21.30
    - 20.37
    - 19.44
    - 18.52
    - 17.59
    - 17
moduleMineEffectBeginHideDistanceProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 25.00
    - 24.07
    - 23.15
    - 22.22
    - 21.30
    - 20.37
    - 19.44
    - 18.52
    - 17.59
    - 17
moduleEffectActivationTimeProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 3000
    - 2889
    - 2778
    - 2667
    - 2556
    - 2444
    - 2333
    - 2222
    - 2111
    - 2000
moduleLimitBundleEffectCountProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
moduleEffectAccelerationProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 12.00
    - 12.67
    - 13.33
    - 14.00
    - 14.67
    - 15.33
    - 16.00
    - 16.67
    - 17.33
    - 18.00
moduleEffectSpeedProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 12.00
    - 12.67
    - 13.33
    - 14.00
    - 14.67
    - 15.33
    - 16.00
    - 16.67
    - 17.33
    - 18.00
moduleSpiderMineEffectEnergyProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 120
    - 120
moduleSpiderMineEffectIdleEnergyDrainRateProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1
    - 1
moduleSpiderMineEffectChasingEnergyDrainRateProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10
    - 10
moduleMineEffectSplashDamageMaxRadiusProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 5.00
    - 5.28
    - 5.56
    - 5.83
    - 6.11
    - 6.39
    - 6.67
    - 6.94
    - 7.22
    - 7.50
moduleMineEffectSplashDamageMinRadiusProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 10.00
    - 10.56
    - 11.11
    - 11.67
    - 12.22
    - 12.78
    - 13.33
    - 13.89
    - 14.44
    - 15.00
moduleMineEffectSplashDamageMinPercentProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 0.50
    - 0.53
    - 0.56
    - 0.58
    - 0.61
    - 0.64
    - 0.67
    - 0.69
    - 0.72
    - 0.75
moduleEffectTargetingDistanceProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 15.00
    - 15.83
    - 16.67
    - 17.50
    - 18.33
    - 19.17
    - 20.00
    - 20.83
    - 21.67
    - 22.50
moduleEffectTargetingPeriodProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.5
    - 0.5
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 90
        - 60
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Damage
      linearInterpolation: false
      upgradeLevel2Values:
        - 700
        - 738
        - 778
        - 817
        - 856
        - 894
        - 933
        - 972
        - 1011
        - 1050
      maxAndMinString:
        - 700-1000
        - 739-1056
        - 778-1111
        - 817-1167
        - 856-1222
        - 894-1278
        - 933-1333
        - 972-1388
        - 1011-1444
        - 1050-1500
      unit: hp
      maxAndMin: true
      format: 0
      spriteUID: 5538887f-b208-4fb4-ac4a-12223cb09fd3
    - name: VisibilityArea
      linearInterpolation: true
      upgradeLevel2Values:
        - 25
        - 17
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: ActivationTime
      linearInterpolation: true
      upgradeLevel2Values:
        - 3
        - 2
      unit: sec
      format: 0.00
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: ExplosionRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 10
        - 15
      unit: m
      format: 0.0
      spriteUID: c1a7c983-c17f-4f35-8514-8a6bc28fb93b
    - name: "Impact"
      linearInterpolation: true
      upgradeLevel2Values:
        - 3
        - 4.5
      unit: hp
      format: 0.0
      spriteUID: 8bf5d2cc-2f2b-4f2a-8d6e-880bcdbf4844
    - name: TargetingRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 15
        - 22.5
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: Speed
      linearInterpolation: true
      upgradeLevel2Values:
        - 12
        - 18
      unit: meters_per_sec
      format: 0.0
      spriteUID: 88babefa-ef53-4242-bfab-e5a7c7c7fb21
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
