order:
  index: 0
unityAsset:
  reference:
    assetGuid: 0867c8653d3a1cd4787716afe09f2568
imageItem:
  spriteUid: 9d71785a-4c4c-4653-9477-4c3f21e16107
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
