priceItem:
  price: 10000
xPriceItem:
  price: 199
imageItem:
  spriteUid: 297517de-51da-4acd-a308-a70b9d5fc0e7
order:
  index: 318
unityAsset:
  reference:
    assetGuid: dcb78e766036213499dce593c09dd435
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
