configPathCollection:
  collection:
    - garage/skin/weapon/flamethrower/m0
    - garage/skin/weapon/freeze/m0
    - garage/skin/weapon/hammer/m0
    - garage/skin/weapon/isis/m0
    - garage/skin/weapon/railgun/m0
    - garage/skin/weapon/ricochet/m0
    - garage/skin/weapon/shaft/m0
    - garage/skin/weapon/thunder/m0
    - garage/skin/weapon/smoky/m0
    - garage/skin/weapon/twins/m0
    - garage/skin/weapon/vulcan/m0
    - garage/skin/tank/dictator/m0
    - garage/skin/tank/hornet/m0
    - garage/skin/tank/hunter/m0
    - garage/skin/tank/mammoth/m0
    - garage/skin/tank/titan/m0
    - garage/skin/tank/viking/m0
    - garage/skin/tank/wasp/m0
    - garage/skin/weapon/flamethrower/m1
    - garage/skin/weapon/freeze/m1
    - garage/skin/weapon/hammer/m1
    - garage/skin/weapon/isis/m1
    - garage/skin/weapon/railgun/m1
    - garage/skin/weapon/ricochet/m1
    - garage/skin/weapon/shaft/m1
    - garage/skin/weapon/thunder/m1
    - garage/skin/weapon/smoky/m1
    - garage/skin/weapon/twins/m1
    - garage/skin/weapon/vulcan/m1
    - garage/skin/tank/dictator/m1
    - garage/skin/tank/hornet/m1
    - garage/skin/tank/hunter/m1
    - garage/skin/tank/mammoth/m1
    - garage/skin/tank/titan/m1
    - garage/skin/tank/viking/m1
    - garage/skin/tank/wasp/m1
