priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: a62553f8-cc69-4793-b06e-5e88d63114c6
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 2cb2621d5f14a0840ab26402dd81b804
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: LEGENDARY
