itemsContainerItem:
  items:
    - itemBundles:
        - marketItem: -1902859834 # Triangle Camo tank paint
      compensation: 6250
      nameLocalizationKey: triangletankpaint
    - itemBundles:
        - marketItem: -2097840184 # Triangle Camo weapon paint
      compensation: 6250
      nameLocalizationKey: triangleweaponpaint
    - itemBundles:
        - marketItem: -683002753 # Digital tank paint
      compensation: 6250
      nameLocalizationKey: digitaltankpaint
    - itemBundles:
        - marketItem: 534589821 # Digital weapon paint
      compensation: 6250
      nameLocalizationKey: digitalweaponpaint
    - itemBundles:
        - marketItem: 1775068808 # May Graffity 1
      compensation: 6250
    - itemBundles:
        - marketItem: -445855153 # Shaft Steel Skin
      compensation: 6250
      nameLocalizationKey: steelShaft
    - itemBundles:
        - marketItem: -833500654 # Mammoth Steel Skin
      compensation: 6250
      nameLocalizationKey: steelMammoth
  rareItems:
    - itemBundles:
        - marketItem: -313951841 # Viking Victory Day skin
      compensation: 6250
      nameLocalizationKey: mayViking
    - itemBundles:
        - marketItem: 1912357269 # Thunder Victory Day skin
      compensation: 6250
      nameLocalizationKey: mayThunder
userItemTemplate:
  userItemTemplate: 1479807574456
unityAsset:
  reference:
    assetGuid: 08a675f3f7f552f439adef049086866b
imageItem:
  spriteUid: 445a7b3c-c094-48b0-bb59-42bfa27c5d53
order:
  index: -3
priceItem:
  price: 0
xPriceItem:
  price: 125
itemPacks:
  forXPrice:
    - 1
    - 3
    - 10
  forPrice:
packPrice:
  packPrice:
    0: 0
  packXPrice:
    1: 125
    3: 335
    10: 1000
