priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: ba3cd2fe-6df2-4313-a1de-5a107851cedb
order:
  index: 1
unityAsset:
  reference:
    assetGuid: 189c751a16697c74eb4804e5e5212ef0
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
