priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 48d78828-7ab7-4d5c-aa55-7502a85f1235
order:
  index: 318
unityAsset:
  reference:
    assetGuid: 67ebb8dd214e25545988bb5e00057c1a
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 5
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
