priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 302
unityAsset:
  reference:
    assetGuid: fd029ec5bb73c7b4cb3abffd29f588f2
imageItem:
  spriteUid: d5105ae4-60a3-409d-904a-13302eed1453
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 10
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
