priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
unityAsset:
  reference:
    assetGuid: d2210ba43ae34cb449fbe600d66041a5
imageItem:
  spriteUid: d406baee-192f-4d22-b981-fa7d10d4d03a
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
