priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 301
unityAsset:
  reference:
    assetGuid: 570827c490b86ff44a5e4a392e21c164
imageItem:
  spriteUid: 92c59c38-a2d4-4a03-9068-80216b4c7b4e
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 6
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
