priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 1ad700c9-ebc1-4f75-a549-3c5c8722fb3f
order:
  index: 1
unityAsset:
  reference:
    assetGuid: 58a25259485b2e44a97091bf771edb8b
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
