priceItem:
  price: 0
xPriceItem:
  price: 499
order:
  index: 100
unityAsset:
  reference:
    assetGuid: 8f957ff62fddc704bb3525061afcb10d
imageItem:
  spriteUid: af19358d-6aa8-4fad-ac4f-0e546fbb9209
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
