priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 302
unityAsset:
  reference:
    assetGuid: 5ec5bee89de0b2748875eb6e2c1e483c
imageItem:
  spriteUid: c9599b8b-5729-4b0d-b0f8-daa38bcb19c4
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
