priceItem:
  price: 5250
xPriceItem:
  price: 249
order:
  index: 200
unityAsset:
  reference:
    assetGuid: d0d8235bfba53e94ab510182566c947b
imageItem:
  spriteUid: 74326992-5e32-4446-8db5-7478155118ab
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
