order:
  index: 0
unityAsset:
  reference:
    assetGuid: fa5510c224c5bad49b938ae375ae25d8
imageItem:
  spriteUid: a5a6f981-c746-4c01-830c-e34294129fa8
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
