priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 8160371e-73d0-40ab-97ea-2a3b375f1b00
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 3c70fcaecb91d984cb3fa014d775ce77
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
