unityAsset:
  reference:
    assetGuid: 4186f957bfbd04a40920cbc4a9ebf3a8
verticalSectorsTargeting:
  workDistance: 1.0e6
  vAngleUp: 9.0
  vAngleDown: 12
  hAngle: 5
  raysPerDegree: 2
ctfTargetEvaluator:
  flagCarrierPriorityBonus: 5
distanceAndAngleTargetEvaluator:
  distanceWeight: 0.65
  angleWeight: 0.35
reticle:
  template: 636100801360863080
  configPath: /battle/reticle
kickbackCameraShakerConfig:
  enabled: true
  magnitude: 1.29
  roughness: 4
  fadeInTime: 0.14
  fadeOutTime: 0.43
  posInfluenceX: 0.25
  posInfluenceY: 0.25
  posInfluenceZ: 0.25
  rotInfluenceX: 1
  rotInfluenceY: 1
  rotInfluenceZ: 0
impactCameraShakerConfig:
  enabled: true
  magnitude: 1.0
  roughness: 4
  fadeInTime: 0.14
  fadeOutTime: 0.43
  posInfluenceX: 0.75
  posInfluenceY: 0.75
  posInfluenceZ: 1.25
  rotInfluenceX: 1
  rotInfluenceY: 1
  rotInfluenceZ: 1
hitFeedbackSoundsPlayingSettings:
  delay: -1
  volume: 1
  removeOnKillSound: true
