priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: f891715f-f4a6-4e73-83ab-ec3ad9dc16d9
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 9c2f7a43fbeefe744bc5b2079d2bb2df
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
