priceItem:
  price: 0
xPriceItem:
  price: 213
order:
  index: 1
unityAsset:
  reference:
    assetGuid: 908885f8cab57b14d81cde0ceec31f5a
imageItem:
  spriteUid: de2ad2df-6a85-4fc6-a25f-49a75be09500
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
