warmupResources:
  assetGuids:
    - 26b98943b6b8def4ba40e624a78a7077
    - e38825a7ddcd74f4681e57bde02d4642
    - 5c6e6e565ce01944f904f98e068610e0
    - e0800ca59714e704c9efa968f557b28f
    - 325fabab2d3c5d445bfd7166cbf5f428
    - 748365659dcd2474abe3f834f5f39d70
    - 055ecdbb4b1bccd45a89740103e6cefd
    - e71666ab1a2e03e48b663e3e6b055ae7
    - be0b14bd81856a74c90dbbb19d37ff5c
    - 099afd48dc1281d4ca5a74f0fa1518c5
    - 18ea98769fbeae84c8ba5a6b4cebf870
    - 21988f3eb5cd64b42923307fbf7f52d7
    - 54c645b58f8519b49a811a1f07b5a727
    - c946619e7e8ee724fa135c4bdbf91e5b
    - 4186f957bfbd04a40920cbc4a9ebf3a8
    - 115722a4d4d1eee4d9415ef19250b00a
    - 1dc2b559cff507c4c906d84dba713b52
    - a1075892035a5ed4c96d4c2713a312a5
