priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 302
unityAsset:
  reference:
    assetGuid: 7107d7d92149fb84fadbf20a2a261773
imageItem:
  spriteUid: 390c2019-520b-46af-a83a-df970e537406
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 10
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
