priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 1
unityAsset:
  reference:
    assetGuid: 156d0f272691c8349a5fa9c2f47d26ca
imageItem:
  spriteUid: 55202ee8-bf26-41ee-857b-8786a2700a7f
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
