moduleCooldownProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 81000
    - 78000
    - 75000
    - 72000
    - 69000
    - 66000
    - 63000
    - 60000
    - 57000
    - 54000
moduleAmmunitionProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
moduleEffectDurationProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 8000
    - 8444
    - 8889
    - 9333
    - 9778
    - 10222
    - 10667
    - 11111
    - 11556
    - 12000
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 81
        - 54
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Duration
      linearInterpolation: true
      upgradeLevel2Values:
        - 8
        - 12
      unit: sec
      format: 0.0
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
