priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 4e601e25-3f14-4f1f-9a6a-681875534fdc
order:
  index: 307
unityAsset:
  reference:
    assetGuid: 102b164447d45154093d5b51dd55fed8
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 5
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
