imageItem:
  spriteUid: 445e7559-7a41-4246-a9b4-30facf43cad9
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 5e2526a5cf8fad94cb65b5704cd30fdd
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
