order:
  index: 1
unityAsset:
  reference:
    assetGuid: cee45a70163e4f340bb8eef27c1f88a5
imageItem:
  spriteUid: f68c4c99-ec9e-422a-b166-ed4b8672d4b6
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
