xcrystalsPack:
  amount: 0
  bonus: 0
crystalsPack:
  amount: 0
  bonus: 0
countableItemsPack:
  pack:
    -1667426315: 9 # smuggler's cards
    947348559: 5500 # crystals
    1317350822: 500 # x-crystals
specialOfferScreen:
  show: false
itemsPackFromConfig:
  pack:
itemUpgradePackFromConfig:
  pack:
goodsPrice:
  price: 0
  currency: ""
steamGoodsPrice:
  priceRatio: 100
  round: 1
  default: false
  active: true
  steamOnly: false
offerConditions:
  finishedOffer:
  startDate:
  battlesCountMin: 1 # 0 == not after battle
offerDuration: #sec
  duration: 259200 # 3 days
  oneShot: true
packId:
  id: 518821154
leagueFirstEntranceSpecialOffer:
  leagueId: 1131431735
  worthItPercent: 200
order:
  index: -5
specialOfferContent:
  salePercent: 40
  highlightTitle: false
  showItemsList: true
goodsDescription:
  description: "Special offer «New League»"
specialOfferLocalizedName:
  name:
    "en": "Special offer «New League»"
    "ru": "Спецпредложение «Новая лига»"
    "tr": "Спецпредложение «Новая лига»"
goodsPrices:
  prices:
    "AED": 41.99
    "ARS": 199
    "AUD": 11.99
    "BRL": 29.99
    "CAD": 11.99
    "CHF": 11.99
    "CLP": 7200
    "CNY": 70
    "COP": 30000
    "CRC": 6500
    "EUR": 11.99
    "GBP": 11.99
    "HKD": 95
    "IDR": 100000
    "ILS": 42
    "INR": 689
    "JPY": 1200
    "KRW": 12000
    "KWD": 3.5
    "KZT": 3999
    "MXN": 179
    "MYR": 35.99
    "NOK": 83.99
    "NZD": 11.99
    "PEN": 35.99
    "PHP": 444
    "PLN": 42
    "QAR": 42
    "RUB": 599
    "SAR": 47.99
    "SGD": 15
    "THB": 349
    "TRY": 47.99
    "TWD": 359
    "UAH": 239
    "USD": 11.99
    "UYU": 349
    "VND": 250000
    "ZAR": 139
