priceItem:
  price: 2000
xPriceItem:
  price: 400
userItemTemplate:
  userItemTemplate: 1435138285320
itemIcon:
  spriteUid: d4a79e51-88a7-41b6-a06b-32d970643d0d
order:
  index: 10
crystalsPurchaseUserRankRestriction:
  restrictionValue: 13
minDamageProperty:
  initialValue: 285.6
  finalValue: 285.6
maxDamageProperty:
  initialValue: 285.6
  finalValue: 285.6
energyChargePerShotProperty:
  initialValue: 0.200
  finalValue: 0.200
reloadTimeProperty:
  initialValue: 0.700
  finalValue: 0.700
energyRechargeSpeedProperty:
  initialValue: 0.143
  finalValue: 0.143
bulletSpeedProperty:
  initialValue: 110.000
  finalValue: 110.000
bulletRadiusProperty:
  initialValue: 0.800
  finalValue: 0.800
maxDamageDistanceProperty:
  initialValue: 61.696
  finalValue: 61.696
minDamageDistanceProperty:
  initialValue: 110.000
  finalValue: 110.000
minDamagePercentProperty:
  initialValue: 59.130
  finalValue: 59.130
impactProperty:
  initialValue: 2.000
  finalValue: 2.000
kickbackProperty:
  initialValue: 1.000
  finalValue: 1.000
visualProperties:
  mainProperties:
    - name: Damage
      normalizedValue: 0.2
    - name: Range
      normalizedValue: 0.57
    - name: FireRate
      normalizedValue: 0.4
  properties:
    - name: DPM
      initialValue: 24480
      finalValue: 24480
    - name: Damage per Projectile
      initialValue: 285.6
      finalValue: 285.6
      format: 0.0
    - name: Reload Time
      initialValue: 0.7
      finalValue: 0.7
      format: 0.0
      unit: sec
    - name: Projectile Speed
      initialValue: 110
      finalValue: 110
      unit: meters_per_sec
    - name: Max Damage Distance
      initialValue: 61.7
      finalValue: 61.7
      format: 0.0
      unit: m
    - name: Attack Distance
      initialValue: 110
      finalValue: 110
      unit: m
    - name: Impact
      initialValue: 2
      finalValue: 2
      format: 0
...