purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
unityAsset:
  reference:
    assetGuid: a32ef8afbd933ce479763e387bd752de
imageItem:
  spriteUid: 961531d2-0ba1-43ad-bdfb-13275c73b392
itemRarity:
  rarityType: COMMON
