priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
unityAsset:
  reference:
    assetGuid: 844389a92dd5a5d4bba1441d38d7c4eb
imageItem:
  spriteUid: 4c9d7de7-abfc-4345-a167-a86d56801f8f
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
