priceItem:
  price: 5250
xPriceItem:
  price: 249
order:
  index: 200
unityAsset:
  reference:
    assetGuid: 65d05f59d7533394da64ef3b5e164475
imageItem:
  spriteUid: 41b23f98-b52a-48e0-8e96-83c8ca9f9d6c
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
