priceItem:
  price: 600
xPriceItem:
  price: 120
order:
  index: 3
crystalsPurchaseUserRankRestriction:
  restrictionValue: 4
hullType:
  hullType: HEAVY
health:
  initialValue: 3400.000
  finalValue: 3400.000
weight:
  initialValue: 4026.667
  finalValue: 4026.667
damping:
  initialValue: 2100.000
  finalValue: 2100.000
speed:
  initialValue: 6.567
  finalValue: 6.567
acceleration:
  initialValue: 14.744
  finalValue: 14.744
reverseAcceleration:
  initialValue: 6.674
  finalValue: 6.674
sideAcceleration:
  initialValue: 21.880
  finalValue: 21.880
turnSpeed:
  initialValue: 74.000
  finalValue: 74.000
turnAcceleration:
  initialValue: 82.789
  finalValue: 82.789
reverseTurnAcceleration:
  initialValue: 152.333
  finalValue: 152.333
turretTurnSpeedProperty:
  initialValue: 93.333
  finalValue: 93.333
turretTurnAccelerationProperty:
  initialValue: 67.667
  finalValue: 67.667
visualProperties:
  mainProperties:
    - name: Armor
      normalizedValue: 1.0
    - name: Mobility
      normalizedValue: 0.491
  properties:
    - name: Armor
      initialValue: 3400
      finalValue: 3400
    - name: Weight
      initialValue: 40.3
      finalValue: 40.3
      format: 0.0
      unit: t
    - name: Speed
      initialValue: 6.57
      finalValue: 6.57
      format: 0.00
      unit: meters_per_sec
    - name: Acceleration
      initialValue: 14.7
      finalValue: 14.7
      format: 0.0
      unit: meters_per_sec
    - name: Turning Speed
      initialValue: 74
      finalValue: 74
      unit: degrees_per_sec
    - name: TurretRotationSpeed
      initialValue: 93.3
      finalValue: 93.3
      format: 0.0
      unit: degrees_per_sec
...
