priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: f97c9963-b158-4e0e-b977-434e357230c5
order:
  index: 317
unityAsset:
  reference:
    assetGuid: 5804a3be41159234f9d5b610ea21b35e
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
