itemsContainerItem:
  items:
    - itemBundles:
        - marketItem: -571325445 # Red Star
      compensation: 6250
    - itemBundles:
        - marketItem: -963712308 # Vulcan Red
      compensation: 6250
    - itemBundles:
        - marketItem: 189220223 # Vulcan Blue
      compensation: 6250
    - itemBundles:
        - marketItem: 1479495495 # dean_cunningham
      compensation: 6250
    - itemBundles:
        - marketItem: -1130044595 # evgeny_romanov
      compensation: 6250
    - itemBundles:
        - marketItem: 706204327 # magnus_grim
      compensation: 6250
    - itemBundles:
        - marketItem: -880569858 # oskar_khrom
      compensation: 6250
    - itemBundles:
        - marketItem: -1330873567 # professor
      compensation: 6250
    - itemBundles:
        - marketItem: 605003762 # yamamoto_tsunetomo
      compensation: 6250
  rareItems:
    - itemBundles:
        - marketItem: -1141123658 # Smoky skin
    - itemBundles:
        - marketItem: 247232443 # Hunter skin
    - itemBundles:
        - marketItem: 300183087 # 23 feb 2019 Mars Stars Paint
    - itemBundles:
        - marketItem: -480997961 # vladimir_repin
    - itemBundles:
        - marketItem: 1953932916 # garcia_lopez
    - itemBundles:
        - marketItem: -250346840 # Shaft Lighting
userItemTemplate:
  userItemTemplate: 1479807574456
unityAsset:
  reference:
    assetGuid: 1507c7be2518e584186c0cb75ac29ab0
imageItem:
  spriteUid: d013befc-ef3e-43c1-bda4-684912ea5d2f
order:
  index: 0
priceItem:
  price: 0
xPriceItem:
  price: 125
itemPacks:
  forXPrice:
    - 1
    - 3
    - 10
  forPrice:
packPrice:
  packPrice:
    0: 0
  packXPrice:
    1: 125
    3: 335
    10: 1000
