priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 715184f0-d992-4a0d-85fb-3a377e371649
order:
  index: 3
unityAsset:
  reference:
    assetGuid: a2c809ef88907374fbf6114b92664e09
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
