moduleUpgradablePowerConfig:
  level2PowerByTier:
    - - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
    - - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
    - - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
