priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 4fadd0b9-00ed-4882-a51d-c9c911751b71
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 052532f61f6d07a4680b98d2121215e6
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: LEGENDARY
