tutorialData:
  stepsPath: "garage/tutorial/steps/backHitDamageTutorial/"
  tutorialId: 1662017877
  forNewPlayer: true
  steps:
    1: 1504002856142 # show popup

tutorialRequiredCompletedTutorials:
  tutorialsIds:
    - -1969453819 # hull control
    - -325846104 # turret control
