priceItem:
  price: 0
xPriceItem:
  price: 499
order:
  index: 100
unityAsset:
  reference:
    assetGuid: 0905d50392bad1049890985e32c7c4c1
imageItem:
  spriteUid: 3a130d1f-9c56-43c6-b4d6-522d5070e4c7
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
