priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
unityAsset:
  reference:
    assetGuid: 376e90feecf67f2419c182a472be1f72
imageItem:
  spriteUid: c37b1c6a-8f6b-4ee4-8f41-0f7f45e30c77
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
