priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 200
unityAsset:
  reference:
    assetGuid: f5f3cb37d6e246b4c9d1e06366a53687
imageItem:
  spriteUid: 66f54a99-7d19-43c6-a33d-16e9412d8cf4
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
