priceItem:
  price: 0
xPriceItem:
  price: 0
userItemTemplate:
  userItemTemplate: 1433406776150
itemIcon:
  spriteUid: 4053fb51-0d28-4afb-97a4-c66ce972b375
order:
  index: 1
crystalsPurchaseUserRankRestriction:
  restrictionValue: 0
minDamageProperty:
  initialValue: 319.828
  finalValue: 319.828
maxDamageProperty:
  initialValue: 330.172
  finalValue: 330.172
reloadTimeProperty:
  initialValue: 1.300
  finalValue: 1.300
criticalDamageProperty:
  initialValue: 325.000
  finalValue: 325.000
startCriticalProbabilityProperty:
  initialValue: 0.200
  finalValue: 0.200
afterCriticalHitProbabilityProperty:
  initialValue: -0.500
  finalValue: -0.500
maxCriticalProbabilityProperty:
  initialValue: 0.950
  finalValue: 0.950
criticalProbabilityDeltaProperty:
  initialValue: 0.100
  finalValue: 0.100
maxDamageDistanceProperty:
  initialValue: 83.091
  finalValue: 83.091
minDamageDistanceProperty:
  initialValue: 128.261
  finalValue: 128.261
minDamagePercentProperty:
  initialValue: 52.174
  finalValue: 52.174
impactProperty:
  initialValue: 2.500
  finalValue: 2.500
kickbackProperty:
  initialValue: 3.000
  finalValue: 3.000
visualProperties:
  mainProperties:
    - name: Damage
      normalizedValue: 0.268
    - name: Range
      normalizedValue: 0.741
    - name: FireRate
      normalizedValue: 0.80
  properties:
    - name: DPM
      initialValue: 15000
      finalValue: 15000
    - name: Damage
      initialValue: 325
      finalValue: 325
    - name: Critical Damage
      initialValue: 325
      finalValue: 325
    - name: Critical Chance
      initialValue: 30
      finalValue: 30
      unit: percent
    - name: Reload Time
      initialValue: 1.3
      finalValue: 1.3
      format: 0.0
      unit: sec
    - name: Max Damage Distance
      initialValue: 83.1
      finalValue: 83.1
      format: 0.0
      unit: m
    - name: Attack Distance
      initialValue: 128.3
      finalValue: 128.3
      format: 0.0
      unit: m
    - name: Impact
      initialValue: 2.5
      finalValue: 2.5
      format: 0.0
...
