priceItem:
  price: 0
xPriceItem:
  price: 349
order:
  index: 200
unityAsset:
  reference:
    assetGuid: 5965dd45a436e1849b21f9d5911b99d1
imageItem:
  spriteUid: 1b4c7ec8-d063-4b3f-a35c-3ea475a8b102
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
