priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 302
unityAsset:
  reference:
    assetGuid: 45311421bb461d341b18f2286cad2c86
imageItem:
  spriteUid: d9e68427-3d7f-4b86-98e0-35e499b2947c
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
