priceItem:
  price: 0
xPriceItem:
  price: 499
order:
  index: 100
unityAsset:
  reference:
    assetGuid: 4e7731cf3d8dbd942b983553f857a3cb
imageItem:
  spriteUid: 0f350e51-9de6-441a-b854-7695d25f8f9d
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
