---
descriptionItem:
  name: "Hacker's blueprints"
  description: "Contains at least 61 blueprints with 5 blueprints of Tier-2 included. Has a chance of containing Tier-3 blueprints"
descriptionBundleItem:
  names: { }
