priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 41f7d5e148087ce41b40a73a3dbfda5f
imageItem:
  spriteUid: 1d99200a-aa20-4246-9a08-1396ba0fa52f
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
