priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 301
unityAsset:
  reference:
    assetGuid: 61a0ecaf1138fcd408b1e3defbbb3079
imageItem:
  spriteUid: 904def88-8064-4944-82a5-ecc8f2b82d53
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 6
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
