priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 0
unityAsset:
  reference:
    assetGuid: cd5af149c81d7354285a042307396e2d
imageItem:
  spriteUid: 4cdf55b1-ae79-4ad3-88eb-9f8ccddb8cd7
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
