itemsContainerItem:
  items:
    - itemBundles:
        - marketItem: 139596834 # freeze xmas
      compensation: 42500
    - itemBundles:
        - marketItem: 72041592 # wasp xmas
      compensation: 42500
    - itemBundles:
        - marketItem: -1141123658 # smoky defender
      compensation: 42500
    - itemBundles:
        - marketItem: 247232443 # hunter defender
      compensation: 42500
    - itemBundles:
        - marketItem: -305773183 # isis bumblebee
      compensation: 42500
    - itemBundles:
        - marketItem: -1648311780 # wasp bumblebee
      compensation: 42500
    - itemBundles:
        - marketItem: 732611697 # dictator dreadnought
      compensation: 42500
    - itemBundles:
        - marketItem: 1770762539 # thunder dreadnought
      compensation: 42500
    - itemBundles:
        - marketItem: 110176853 # hunter may
      compensation: 42500
    - itemBundles:
        - marketItem: 963790407 # hornet may
      compensation: 42500
    - itemBundles:
        - marketItem: -313951841 # viking may
      compensation: 42500
    - itemBundles:
        - marketItem: 1912357269 # thunder may
      compensation: 42500
    - itemBundles:
        - marketItem: -1398640396 # smoky may
      compensation: 42500
    - itemBundles:
        - marketItem: 98615071 # railgun may
      compensation: 42500
    - itemBundles:
        - marketItem: 602602131 # flamethrower dreadnought
      compensation: 42500
    - itemBundles:
        - marketItem: -2009337684 # wasp dreadnought
      compensation: 42500

  rareItems:

userItemTemplate:
  userItemTemplate: 1479807574456
unityAsset:
  reference:
    assetGuid: 79d87c318b4f8394bbede939bcc2cb1c
imageItem:
  spriteUid: 13ddb55b-4f4a-4603-8e76-f191d58b5dd1
order:
  index: -2
priceItem:
  price: 0
xPriceItem:
  price: 0
itemPacks:
  forXPrice:
    - 1
    - 3
    - 10
  forPrice:
packPrice:
  packPrice:
    0: 0
  packXPrice:
    1: 125
    3: 335
    10: 1000
