priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 86245f78-252d-40d7-846b-10c0bd479001
order:
  index: 310
unityAsset:
  reference:
    assetGuid: dd2853e28d4c36d4aa4dd178bbacbb76
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 5
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
