priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 7736a300-89b3-4534-93c6-395b2e13aca8
order:
  index: 0
unityAsset:
  reference:
    assetGuid: 396665a9bf93f4ba0856767de3d0b919
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: LEGENDARY
