priceItem:
  price: 5250
xPriceItem:
  price: 249
order:
  index: 200
unityAsset:
  reference:
    assetGuid: 1a2b7bb4d8dbff94098ddecf9a676491
imageItem:
  spriteUid: 8b69419a-cdb0-4ccb-969b-9fd37bcaf9eb
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
