bonusRegionAssets:
  doubleDamageAssetGuid: a8219a2ea9ddb46ffb9c6c0f642c65c5
  doubleArmorAssetGuid: bc43fb2de7afd4ac2a896e1427d6eea0
  repairKitAssetGuid: 791c0e6337ecf4f31bb4a1a98054be72
  speedBoostAssetGuid: 510b4ce311b1d4dc887f4f3c4a020cbe
  goldAssetGuid: b9f6b34e135c7451e921198af40fcc9e
