---
descriptionItem:
  name: Scout blueprints
  description: "This container holds a minimum of 190 blueprints of Jump Impact, External Impact, Fire Ring, Explosive Mass, Sapper and Kamikadze modules."
descriptionBundleItem:
  names: { }
