priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 5d35c7ef-3938-4532-9424-7b739b00fa72
order:
  index: 0
unityAsset:
  reference:
    assetGuid: c747f19116411114da71f1ce792b9e74
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: LEGENDARY
