order:
  index: 1
unityAsset:
  reference:
    assetGuid: 525a8ebb34244cd44aa920357a9c18e8
imageItem:
  spriteUid: ed0b892f-eedd-4265-8d29-efb7d77eb18c
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
