priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
unityAsset:
  reference:
    assetGuid: 1f54b6c629f252a4993321efd5a46098
imageItem:
  spriteUid: 25d301ba-6142-4a81-8dc5-d7878ecd2e34
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
