priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: 295b3491-572c-4b6b-a7cd-53f5a05722f3
order:
  index: 1
unityAsset:
  reference:
    assetGuid: 4e868134cab537545bbf05ddce4c5ab4
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
