priceItem:
  price: 1800
xPriceItem:
  price: 360
order:
  index: 4
crystalsPurchaseUserRankRestriction:
  restrictionValue: 7
hullType:
  hullType: MEDIUM
health:
  initialValue: 2300.000
  finalValue: 2300.000
weight:
  initialValue: 2640.000
  finalValue: 2640.000
damping:
  initialValue: 1300.000
  finalValue: 1300.000
speed:
  initialValue: 11.100
  finalValue: 11.100
acceleration:
  initialValue: 12.692
  finalValue: 12.692
reverseAcceleration:
  initialValue: 12.067
  finalValue: 12.067
sideAcceleration:
  initialValue: 19.320
  finalValue: 19.320
turnSpeed:
  initialValue: 106.000
  finalValue: 106.000
turnAcceleration:
  initialValue: 122.876
  finalValue: 122.876
reverseTurnAcceleration:
  initialValue: 251.000
  finalValue: 251.000
turretTurnSpeedProperty:
  initialValue: 120.000
  finalValue: 120.000
turretTurnAccelerationProperty:
  initialValue: 129.000
  finalValue: 129.000
visualProperties:
  mainProperties:
    - name: Armor
      normalizedValue: 0.675
    - name: Mobility
      normalizedValue: 0.830
  properties:
    - name: Armor
      initialValue: 2300
      finalValue: 2300
    - name: Weight
      initialValue: 26.4
      finalValue: 26.4
      format: 0.0
      unit: t
    - name: Speed
      initialValue: 11.1
      finalValue: 11.1
      format: 0.0
      unit: meters_per_sec
    - name: Acceleration
      initialValue: 12.7
      finalValue: 12.7
      format: 0.0
      unit: meters_per_sec
    - name: Turning Speed
      initialValue: 106
      finalValue: 106
      unit: degrees_per_sec
    - name: TurretRotationSpeed
      initialValue: 120
      finalValue: 120
      format: 0
      unit: degrees_per_sec
...
