moduleCooldownProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 50000
    - 48148
    - 46296
    - 44444
    - 42593
    - 40741
    - 38889
    - 37037
    - 35185
    - 33333
moduleAmmunitionProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
moduleEffectDurationProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 7000
    - 7389
    - 7778
    - 8167
    - 8556
    - 8944
    - 9333
    - 9722
    - 10111
    - 10500
moduleArmorEffectProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.86
    - 0.67
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 50
        - 33.3
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Duration
      linearInterpolation: true
      upgradeLevel2Values:
        - 7
        - 10.5
      unit: sec
      format: 0.0
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: DamageReduction
      linearInterpolation: true
      upgradeLevel2Values:
        - 14
        - 33
      unit: percent
      format: 0
      spriteUID: ef31e149-aafc-419b-8a53-7e6393399092
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
