---
descriptionItem:
  name: Чертежи контрабандиста
  description: "В этом контейнере содержится 110 и более чертежей, в том числе не менее трёх чертежей Тира-3 и не менее шести чертежей Тира-2."
descriptionBundleItem:
  names: { }
