priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 302
unityAsset:
  reference:
    assetGuid: 0f9d82e586286f74bb57d97ac5616a6a
imageItem:
  spriteUid: 98746fb1-a9b0-4f4a-8ea8-f4f9f0b61273
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 10
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: COMMON
