priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: a0e79534-b271-4ee2-a431-2a471a93f639
order:
  index: 1
unityAsset:
  reference:
    assetGuid: e7232d5328976d848a68bd3562499d5b
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
