priceItem:
  price: 0
xPriceItem:
  price: 0
imageItem:
  spriteUid: d0fbf24a-9665-4a4e-80db-6064d97ac098
order:
  index: 207
unityAsset:
  reference:
    assetGuid: ada326385efb3cc4580737a6892c826a
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: RARE
