order:
  index: 0
unityAsset:
  reference:
    assetGuid: 6c73e7eb0afa7744aba9da28e05e38c6
imageItem:
  spriteUid: 84521558-7e74-4eee-8ef5-cfa682b4e9e4
purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
itemRarity:
  rarityType: EPIC
